### ISSUE TITLE
mypy==0.620 compatibility issue

### ISSUE THREAD

**Issue by pawelswiecki** [ericvsmith/dataclasses#132] opened 2018-07-11 11:54 UTC
**Versions**

- `Python 3.6.5`

- `mypy==0.620+dev.bc0b551d8df2baadc44f0c3b0b801fcc12119658`

- `dataclasses==0.6`

**What's wrong**

```
$ cat f2.py 
from dataclasses import dataclass
print('works!')
$ python f2.py 
works!
$ mypy f2.py 
f2.py:1: error: Cannot find module named 'dataclasses'
f2.py:1: note: (Perhaps setting MYPYPATH or using the "--ignore-missing-imports" flag would help)
```

So the natural way is to use MYPYPATH to point to the specific package, `dataclasses` in this case. The problem is `dataclasses` package is installed directly in `site-packages` (`virtual_env_path/lib/python3.6/site-packages/dataclasses.py` in my case), and it's an error (and a bad idea) to pass the whole `site-packages` to MYPYPATH. 

When I manually move the file from `/site-packages/dataclasses.py` to `/site-packages/dataclasses/dataclasses.py` and pass the path to MYPYPATH it's working as expected: no mypy error. Unfortunately, this is not the solution I can use.

I reported this issue on mypy page (https://github.com/python/mypy/issues/5342) and was told that:

> The backport package can fix this by including stubs (presumably the same ones that are in typeshed) and marking itself as typed by using `py.typed`.

Can anything be done about it? I cannot migrate to Python 3.7 yet and would benefit much from mypy actually understanding dataclasses.

**Comment by ericvsmith** [comment] 2018-07-13 22:08
Have you tried installing the stubs yourself? I'd like to know that it works before adding it to the backport.

**Comment by pawelswiecki** [comment] 2018-07-16 16:24
I just tried and failed. 

1. Copied `https://github.com/python/typeshed/blob/master/stdlib/3.7/dataclasses.pyi` to my repo.

2. Run mypy with `MYPYPATH` env var.

3. Getting even more errors:

```python

project_path/stubs/dataclasses.pyi:37: error: Overloaded function signatures 1 and 3 overlap with incompatible return types
project_path/stubs/dataclasses.pyi:42: error: Overloaded function signatures 2 and 3 overlap with incompatible return types  # new error
project_path/module/file.py:33: error: "field" does not return a value  # new error
project_path/module/file.py:127: error: Too many arguments for "MyDataclass"  # old error
```

Line 33 is:

```python

field1: Optional[str] = field(init=False, default=None)

```

Line 127 is:

```python

MyDataclass(field1='foo')
```

I may be doing something wrong.

Also, this solution, even if worked, would be cumbersome, since I'd have to manually update all my repos in which I use dataclasses. It's not that bad, but doing it by bumping lib version would be more convenient.

**Comment by pawelswiecki** [comment] 2018-07-17 09:20
By the way, I have some ideas of dataclass enhancements (I am using the backported version for some time now). Where should I post them: here, on Python's official issue tracker, on python-ideas, python-dev (probably not there), elsewhere?

**Comment by ericvsmith** [comment] 2018-07-17 09:31
@pawelswiecki : I'd bring it up on python-ideas.

**Comment by reinhrst** [comment] 2018-07-18 14:12
It does work for me to add the stub file to the package:

In `site-packages/`:

- move the `dataclasses.py` file to `dataclasses/__init__.py`
- add an empty `dataclasses/py.typed` file (see https://www.python.org/dev/peps/pep-0561/)
- Actually, it works for me with or without the `https://github.com/python/typeshed/blob/master/stdlib/3.7/dataclasses.pyi` as `dataclasses/__init__.pyi`. However I'm sure there are some situations that need this stub file.

Afterwards mypy is able to check my dataclasses (check the `__init__()` method). Not sure about what else.

**Comment by pawelswiecki** [comment] 2018-07-18 15:43
I cannot move dataclasses.py into a dictionary, since deployment scripts would have to be modified, which is out of the question, unfortunately.

**Comment by reinhrst** [comment] 2018-07-19 09:14
My response was a reply to @ericvsmith 's request to check if installing the stubs work. I suggest the dataclasses package gets reworked into this format (rather than just installing the dataclasses.py file), so that it can contain a `py.typed` file (or maybe there is a better solution that I don't know about)

**Comment by pawelswiecki** [comment] 2018-07-19 15:36
Oh, right. Yes, this is the easiest approach, I think.

**Comment by ericvsmith** [comment] 2018-07-20 19:33
Does this problem only exist in the 3.6 backport version of dataclasses? I apologize for not being very familiar with stubs. Do the stubs work differently with the 3.7 stdlib version of dataclasses?

**Comment by gvanrossum** [comment] 2018-07-20 23:00
ATM the typeshed stubs for dataclasses are only present for 3.7:
https://github.com/python/typeshed/blob/master/stdlib/3.7/dataclasses.pyi

It makes sense to add a copy of that file to the backport, and for that to
work the backport should indeed be turned into a directory. It should also
contain a py.typed file (see PEP 561).

**Comment by micseydel** [comment] 2018-08-02 18:12
@pawelswiecki did you end up getting a solution? I'm having this issue with Python 3.7 and mypy 0.620 on OS X, no backports.

Using MYPYPATH to specify a directory containing manually downloaded dataclasses.pyi gives me "invalid syntax" on line 7 (the first non-whitespace character).

**Comment by pawelswiecki** [comment] 2018-08-06 11:57
I did not. 

It's strange that the same problem occurs for Python 3.7: dataclasses should work with mypy==0.620 out of the box.

**Comment by micseydel** [comment] 2018-08-06 22:32
Just tried to reproduce on Linux, and got a different issue that was solved by adding `--python-version 3.7`. Tried to repro on the same OS X project as before and did, but then that same flag fixed the different issue. Doesn't help you, unfortunately, but might help others coming across this thread, even though it's a workaround more than a fix.

**Comment by gvanrossum** [comment] 2018-08-07 14:47
This should be solved once https://github.com/python/typeshed/pull/2354 is merged (and a mypy release including that is distributed, probably mypy 0.620).

**Comment by gvanrossum** [comment] 2018-08-07 19:01
That PR got merged; you can close this issue now, or you can keep it open until mypy 0.630 is out.

**Comment by ericvsmith** [comment] 2018-08-08 01:10
Thanks for the info. I'll wait until 0.630 is out and I can verify it.

**Comment by huyz** [comment] 2021-11-06 14:13
@ericvsmith What's the status of this issue?

I'm curious because I'm getting a similar error with py3.6, mypy 0.910, and dataclasses 0.8
```
error: Library stubs not installed for "dataclasses" (or incompatible with Python 3.6)
```

**Comment by ericvsmith** [comment] 2021-11-06 14:51
@huyz : It seems some of the above information is contradictory. I'm not a big mypy user. but I'm willing to look at a PR.

**Comment by huyz** [comment] 2021-11-06 16:23
@ericvsmith Never mind, mypy has recently changed and we now have to do `mypy --install-types` to get the types.

Separate question: the download [types](https://pypi.org/project/types-dataclasses/) is version 0.6.1, while dataclasses is at 0.8.  I guess you don't maintain these types then?

**Comment by ericvsmith** [comment] 2021-11-06 16:51
I'm glad you figured it out.

Correct: I don't maintain the types.

I'm going to close this issue, since it seems to work with recent enough versions of everything.

**Closed by ericvsmith** 2021-11-06 16:51 UTC
